/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISomniaAgents,
  ISomniaAgentsInterface,
} from "../../../risk/AgentCatcherOracle.sol/ISomniaAgents";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "callbackAddress",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "callbackSelector",
        type: "bytes4",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "createRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getRequestDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISomniaAgents__factory {
  static readonly abi = _abi;
  static createInterface(): ISomniaAgentsInterface {
    return new Interface(_abi) as ISomniaAgentsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISomniaAgents {
    return new Contract(address, _abi, runner) as unknown as ISomniaAgents;
  }
}
