/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IGhostModeEngine {
  export type GhostTransactionStruct = {
    txId: BigNumberish;
    agent: AddressLike;
    payloadHash: BytesLike;
    sanitizedHash: BytesLike;
    riskLevel: BigNumberish;
    status: BigNumberish;
    riskScore: BigNumberish;
    riskReason: string;
    submittedAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type GhostTransactionStructOutput = [
    txId: bigint,
    agent: string,
    payloadHash: string,
    sanitizedHash: string,
    riskLevel: bigint,
    status: bigint,
    riskScore: bigint,
    riskReason: string,
    submittedAt: bigint,
    resolvedAt: bigint
  ] & {
    txId: bigint;
    agent: string;
    payloadHash: string;
    sanitizedHash: string;
    riskLevel: bigint;
    status: bigint;
    riskScore: bigint;
    riskReason: string;
    submittedAt: bigint;
    resolvedAt: bigint;
  };
}

export interface IGhostModeEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getTransactionStatus"
      | "isApproved"
      | "receiveRiskAssessment"
      | "setEnforcement"
      | "setPrivacyProcessor"
      | "setRiskOracle"
      | "submitTransaction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EngineConfigured"
      | "PrivacyProcessed"
      | "RiskAssessmentComplete"
      | "TransactionSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getTransactionStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveRiskAssessment",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnforcement",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrivacyProcessor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTransactionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveRiskAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEnforcement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrivacyProcessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
}

export namespace EngineConfiguredEvent {
  export type InputTuple = [
    riskOracle: AddressLike,
    privacyProcessor: AddressLike,
    enforcementEnabled: boolean
  ];
  export type OutputTuple = [
    riskOracle: string,
    privacyProcessor: string,
    enforcementEnabled: boolean
  ];
  export interface OutputObject {
    riskOracle: string;
    privacyProcessor: string;
    enforcementEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacyProcessedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    agent: AddressLike,
    metadataStripped: boolean
  ];
  export type OutputTuple = [
    txId: bigint,
    agent: string,
    metadataStripped: boolean
  ];
  export interface OutputObject {
    txId: bigint;
    agent: string;
    metadataStripped: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskAssessmentCompleteEvent {
  export type InputTuple = [
    txId: BigNumberish,
    riskLevel: BigNumberish,
    riskScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    txId: bigint,
    riskLevel: bigint,
    riskScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    txId: bigint;
    riskLevel: bigint;
    riskScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionSubmittedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    agent: AddressLike,
    payloadHash: BytesLike,
    riskOracle: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: bigint,
    agent: string,
    payloadHash: string,
    riskOracle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: bigint;
    agent: string;
    payloadHash: string;
    riskOracle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGhostModeEngine extends BaseContract {
  connect(runner?: ContractRunner | null): IGhostModeEngine;
  waitForDeployment(): Promise<this>;

  interface: IGhostModeEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTransactionStatus: TypedContractMethod<
    [txId: BigNumberish],
    [IGhostModeEngine.GhostTransactionStructOutput],
    "view"
  >;

  isApproved: TypedContractMethod<[txId: BigNumberish], [boolean], "view">;

  receiveRiskAssessment: TypedContractMethod<
    [
      txId: BigNumberish,
      riskLevel: BigNumberish,
      riskScore: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  setEnforcement: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPrivacyProcessor: TypedContractMethod<
    [_privacyProcessor: AddressLike],
    [void],
    "nonpayable"
  >;

  setRiskOracle: TypedContractMethod<
    [_riskOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  submitTransaction: TypedContractMethod<
    [payload: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTransactionStatus"
  ): TypedContractMethod<
    [txId: BigNumberish],
    [IGhostModeEngine.GhostTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<[txId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "receiveRiskAssessment"
  ): TypedContractMethod<
    [
      txId: BigNumberish,
      riskLevel: BigNumberish,
      riskScore: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEnforcement"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrivacyProcessor"
  ): TypedContractMethod<
    [_privacyProcessor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRiskOracle"
  ): TypedContractMethod<[_riskOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTransaction"
  ): TypedContractMethod<[payload: BytesLike], [bigint], "nonpayable">;

  getEvent(
    key: "EngineConfigured"
  ): TypedContractEvent<
    EngineConfiguredEvent.InputTuple,
    EngineConfiguredEvent.OutputTuple,
    EngineConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "PrivacyProcessed"
  ): TypedContractEvent<
    PrivacyProcessedEvent.InputTuple,
    PrivacyProcessedEvent.OutputTuple,
    PrivacyProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RiskAssessmentComplete"
  ): TypedContractEvent<
    RiskAssessmentCompleteEvent.InputTuple,
    RiskAssessmentCompleteEvent.OutputTuple,
    RiskAssessmentCompleteEvent.OutputObject
  >;
  getEvent(
    key: "TransactionSubmitted"
  ): TypedContractEvent<
    TransactionSubmittedEvent.InputTuple,
    TransactionSubmittedEvent.OutputTuple,
    TransactionSubmittedEvent.OutputObject
  >;

  filters: {
    "EngineConfigured(address,address,bool)": TypedContractEvent<
      EngineConfiguredEvent.InputTuple,
      EngineConfiguredEvent.OutputTuple,
      EngineConfiguredEvent.OutputObject
    >;
    EngineConfigured: TypedContractEvent<
      EngineConfiguredEvent.InputTuple,
      EngineConfiguredEvent.OutputTuple,
      EngineConfiguredEvent.OutputObject
    >;

    "PrivacyProcessed(uint256,address,bool)": TypedContractEvent<
      PrivacyProcessedEvent.InputTuple,
      PrivacyProcessedEvent.OutputTuple,
      PrivacyProcessedEvent.OutputObject
    >;
    PrivacyProcessed: TypedContractEvent<
      PrivacyProcessedEvent.InputTuple,
      PrivacyProcessedEvent.OutputTuple,
      PrivacyProcessedEvent.OutputObject
    >;

    "RiskAssessmentComplete(uint256,uint8,uint256,string)": TypedContractEvent<
      RiskAssessmentCompleteEvent.InputTuple,
      RiskAssessmentCompleteEvent.OutputTuple,
      RiskAssessmentCompleteEvent.OutputObject
    >;
    RiskAssessmentComplete: TypedContractEvent<
      RiskAssessmentCompleteEvent.InputTuple,
      RiskAssessmentCompleteEvent.OutputTuple,
      RiskAssessmentCompleteEvent.OutputObject
    >;

    "TransactionSubmitted(uint256,address,bytes32,address,uint256)": TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;
    TransactionSubmitted: TypedContractEvent<
      TransactionSubmittedEvent.InputTuple,
      TransactionSubmittedEvent.OutputTuple,
      TransactionSubmittedEvent.OutputObject
    >;
  };
}
