/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivacyProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeLevel"
      | "agentPrivacyLevel"
      | "ghostEngine"
      | "process"
      | "setAgentLevel"
      | "setEngine"
      | "setGlobalLevel"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentPrivacyLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ghostEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "process",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalLevel",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentPrivacyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ghostEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "process", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalLevel",
    data: BytesLike
  ): Result;
}

export interface PrivacyProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyProcessor;
  waitForDeployment(): Promise<this>;

  interface: PrivacyProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeLevel: TypedContractMethod<[], [bigint], "view">;

  agentPrivacyLevel: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  ghostEngine: TypedContractMethod<[], [string], "view">;

  process: TypedContractMethod<
    [payload: BytesLike, agent: AddressLike],
    [string],
    "nonpayable"
  >;

  setAgentLevel: TypedContractMethod<
    [agent: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEngine: TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;

  setGlobalLevel: TypedContractMethod<
    [level: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeLevel"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentPrivacyLevel"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ghostEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "process"
  ): TypedContractMethod<
    [payload: BytesLike, agent: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentLevel"
  ): TypedContractMethod<
    [agent: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEngine"
  ): TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGlobalLevel"
  ): TypedContractMethod<[level: BigNumberish], [void], "nonpayable">;

  filters: {};
}
