/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentCatcherOracleSol from "./AgentCatcherOracle.sol";
export type { agentCatcherOracleSol };
