// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { GhostModeEngine$Type } from "./GhostModeEngine";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GhostModeEngine"]: GhostModeEngine$Type;
    ["contracts/core/GhostModeEngine.sol:GhostModeEngine"]: GhostModeEngine$Type;
  }

  interface ContractTypesMap {
    ["GhostModeEngine"]: GetContractReturnType<GhostModeEngine$Type["abi"]>;
    ["contracts/core/GhostModeEngine.sol:GhostModeEngine"]: GetContractReturnType<GhostModeEngine$Type["abi"]>;
  }
}
