// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AgentCatcherOracle$Type } from "./AgentCatcherOracle";
import { ISomniaAgents$Type } from "./ISomniaAgents";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentCatcherOracle"]: AgentCatcherOracle$Type;
    ["ISomniaAgents"]: ISomniaAgents$Type;
    ["contracts/risk/AgentCatcherOracle.sol:AgentCatcherOracle"]: AgentCatcherOracle$Type;
    ["contracts/risk/AgentCatcherOracle.sol:ISomniaAgents"]: ISomniaAgents$Type;
  }

  interface ContractTypesMap {
    ["AgentCatcherOracle"]: GetContractReturnType<AgentCatcherOracle$Type["abi"]>;
    ["ISomniaAgents"]: GetContractReturnType<ISomniaAgents$Type["abi"]>;
    ["contracts/risk/AgentCatcherOracle.sol:AgentCatcherOracle"]: GetContractReturnType<AgentCatcherOracle$Type["abi"]>;
    ["contracts/risk/AgentCatcherOracle.sol:ISomniaAgents"]: GetContractReturnType<ISomniaAgents$Type["abi"]>;
  }
}
