// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISomniaAgents$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISomniaAgents",
  "sourceName": "contracts/risk/AgentCatcherOracle.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "agentId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "callbackAddress",
          "type": "address"
        },
        {
          "internalType": "bytes4",
          "name": "callbackSelector",
          "type": "bytes4"
        },
        {
          "internalType": "bytes",
          "name": "payload",
          "type": "bytes"
        }
      ],
      "name": "createRequest",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "requestId",
          "type": "uint256"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getRequestDeposit",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISomniaAgents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISomniaAgents$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/risk/AgentCatcherOracle.sol:ISomniaAgents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISomniaAgents$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISomniaAgents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISomniaAgents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/risk/AgentCatcherOracle.sol:ISomniaAgents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISomniaAgents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISomniaAgents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISomniaAgents$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/risk/AgentCatcherOracle.sol:ISomniaAgents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISomniaAgents$Type["abi"]>>;
}
