// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PrivacyProcessor$Type } from "./PrivacyProcessor";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PrivacyProcessor"]: PrivacyProcessor$Type;
    ["contracts/privacy/PrivacyProcessor.sol:PrivacyProcessor"]: PrivacyProcessor$Type;
  }

  interface ContractTypesMap {
    ["PrivacyProcessor"]: GetContractReturnType<PrivacyProcessor$Type["abi"]>;
    ["contracts/privacy/PrivacyProcessor.sol:PrivacyProcessor"]: GetContractReturnType<PrivacyProcessor$Type["abi"]>;
  }
}
