/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ResponseStruct = { result: BytesLike };

export type ResponseStructOutput = [result: string] & { result: string };

export type RequestStruct = {
  requestId: BigNumberish;
  agentId: BigNumberish;
  requester: AddressLike;
  callbackAddress: AddressLike;
  callbackSelector: BytesLike;
  payload: BytesLike;
  deposit: BigNumberish;
  timestamp: BigNumberish;
};

export type RequestStructOutput = [
  requestId: bigint,
  agentId: bigint,
  requester: string,
  callbackAddress: string,
  callbackSelector: string,
  payload: string,
  deposit: bigint,
  timestamp: bigint
] & {
  requestId: bigint;
  agentId: bigint;
  requester: string;
  callbackAddress: string;
  callbackSelector: string;
  payload: string;
  deposit: bigint;
  timestamp: bigint;
};

export interface AgentCatcherOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LLM_AGENT_ID"
      | "SOMNIA_PLATFORM"
      | "depositAmount"
      | "getRequiredDeposit"
      | "ghostEngine"
      | "handleRiskResult"
      | "processedRequests"
      | "requestAssessment"
      | "requestToTxId"
      | "ruleCategories"
      | "rules"
      | "setEngine"
      | "updateDeposit"
      | "updateRule"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LLM_AGENT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOMNIA_PLATFORM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ghostEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleRiskResult",
    values: [BigNumberish, ResponseStruct[], BigNumberish, RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "processedRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAssessment",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToTxId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleCategories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rules", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRule",
    values: [string, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LLM_AGENT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOMNIA_PLATFORM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ghostEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleRiskResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToTxId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ruleCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateRule", data: BytesLike): Result;
}

export interface AgentCatcherOracle extends BaseContract {
  connect(runner?: ContractRunner | null): AgentCatcherOracle;
  waitForDeployment(): Promise<this>;

  interface: AgentCatcherOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LLM_AGENT_ID: TypedContractMethod<[], [bigint], "view">;

  SOMNIA_PLATFORM: TypedContractMethod<[], [string], "view">;

  depositAmount: TypedContractMethod<[], [bigint], "view">;

  getRequiredDeposit: TypedContractMethod<[], [bigint], "view">;

  ghostEngine: TypedContractMethod<[], [string], "view">;

  handleRiskResult: TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: ResponseStruct[],
      status: BigNumberish,
      arg3: RequestStruct
    ],
    [void],
    "nonpayable"
  >;

  processedRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  requestAssessment: TypedContractMethod<
    [txId: BigNumberish, payload: BytesLike],
    [void],
    "nonpayable"
  >;

  requestToTxId: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  ruleCategories: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  rules: TypedContractMethod<
    [arg0: string],
    [
      [string, boolean, bigint] & {
        category: string;
        enabled: boolean;
        weight: bigint;
      }
    ],
    "view"
  >;

  setEngine: TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;

  updateDeposit: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRule: TypedContractMethod<
    [category: string, enabled: boolean, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LLM_AGENT_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOMNIA_PLATFORM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequiredDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ghostEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleRiskResult"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: ResponseStruct[],
      status: BigNumberish,
      arg3: RequestStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestAssessment"
  ): TypedContractMethod<
    [txId: BigNumberish, payload: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestToTxId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ruleCategories"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rules"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, boolean, bigint] & {
        category: string;
        enabled: boolean;
        weight: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEngine"
  ): TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDeposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRule"
  ): TypedContractMethod<
    [category: string, enabled: boolean, weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
