/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentCatcherOracle } from "./AgentCatcherOracle";
export type { ISomniaAgents } from "./ISomniaAgents";
