// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IGhostModeEngine$Type } from "./IGhostModeEngine";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGhostModeEngine"]: IGhostModeEngine$Type;
    ["contracts/core/IGhostModeEngine.sol:IGhostModeEngine"]: IGhostModeEngine$Type;
  }

  interface ContractTypesMap {
    ["IGhostModeEngine"]: GetContractReturnType<IGhostModeEngine$Type["abi"]>;
    ["contracts/core/IGhostModeEngine.sol:IGhostModeEngine"]: GetContractReturnType<IGhostModeEngine$Type["abi"]>;
  }
}
