// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IGhostModeEngine$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IGhostModeEngine",
  "sourceName": "contracts/core/IGhostModeEngine.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "riskOracle",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "privacyProcessor",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "enforcementEnabled",
          "type": "bool"
        }
      ],
      "name": "EngineConfigured",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "agent",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "metadataStripped",
          "type": "bool"
        }
      ],
      "name": "PrivacyProcessed",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "enum IGhostModeEngine.RiskLevel",
          "name": "riskLevel",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "riskScore",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "reason",
          "type": "string"
        }
      ],
      "name": "RiskAssessmentComplete",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "agent",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "payloadHash",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "riskOracle",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "timestamp",
          "type": "uint256"
        }
      ],
      "name": "TransactionSubmitted",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        }
      ],
      "name": "getTransactionStatus",
      "outputs": [
        {
          "components": [
            {
              "internalType": "uint256",
              "name": "txId",
              "type": "uint256"
            },
            {
              "internalType": "address",
              "name": "agent",
              "type": "address"
            },
            {
              "internalType": "bytes32",
              "name": "payloadHash",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "sanitizedHash",
              "type": "bytes32"
            },
            {
              "internalType": "enum IGhostModeEngine.RiskLevel",
              "name": "riskLevel",
              "type": "uint8"
            },
            {
              "internalType": "enum IGhostModeEngine.TxStatus",
              "name": "status",
              "type": "uint8"
            },
            {
              "internalType": "uint256",
              "name": "riskScore",
              "type": "uint256"
            },
            {
              "internalType": "string",
              "name": "riskReason",
              "type": "string"
            },
            {
              "internalType": "uint256",
              "name": "submittedAt",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "resolvedAt",
              "type": "uint256"
            }
          ],
          "internalType": "struct IGhostModeEngine.GhostTransaction",
          "name": "tx",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        }
      ],
      "name": "isApproved",
      "outputs": [
        {
          "internalType": "bool",
          "name": "approved",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        },
        {
          "internalType": "enum IGhostModeEngine.RiskLevel",
          "name": "riskLevel",
          "type": "uint8"
        },
        {
          "internalType": "uint256",
          "name": "riskScore",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "reason",
          "type": "string"
        }
      ],
      "name": "receiveRiskAssessment",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bool",
          "name": "_enabled",
          "type": "bool"
        }
      ],
      "name": "setEnforcement",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_privacyProcessor",
          "type": "address"
        }
      ],
      "name": "setPrivacyProcessor",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_riskOracle",
          "type": "address"
        }
      ],
      "name": "setRiskOracle",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "payload",
          "type": "bytes"
        }
      ],
      "name": "submitTransaction",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "txId",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IGhostModeEngine",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IGhostModeEngine$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/core/IGhostModeEngine.sol:IGhostModeEngine",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IGhostModeEngine$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IGhostModeEngine",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IGhostModeEngine$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/core/IGhostModeEngine.sol:IGhostModeEngine",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IGhostModeEngine$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IGhostModeEngine",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IGhostModeEngine$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/core/IGhostModeEngine.sol:IGhostModeEngine",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IGhostModeEngine$Type["abi"]>>;
}
