/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "GhostModeEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GhostModeEngine__factory>;
    getContractFactory(
      name: "IGhostModeEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGhostModeEngine__factory>;
    getContractFactory(
      name: "PrivacyProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivacyProcessor__factory>;
    getContractFactory(
      name: "AgentCatcherOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentCatcherOracle__factory>;
    getContractFactory(
      name: "ISomniaAgents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaAgents__factory>;

    getContractAt(
      name: "GhostModeEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GhostModeEngine>;
    getContractAt(
      name: "IGhostModeEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGhostModeEngine>;
    getContractAt(
      name: "PrivacyProcessor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivacyProcessor>;
    getContractAt(
      name: "AgentCatcherOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentCatcherOracle>;
    getContractAt(
      name: "ISomniaAgents",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaAgents>;

    deployContract(
      name: "GhostModeEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GhostModeEngine>;
    deployContract(
      name: "IGhostModeEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGhostModeEngine>;
    deployContract(
      name: "PrivacyProcessor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyProcessor>;
    deployContract(
      name: "AgentCatcherOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentCatcherOracle>;
    deployContract(
      name: "ISomniaAgents",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgents>;

    deployContract(
      name: "GhostModeEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GhostModeEngine>;
    deployContract(
      name: "IGhostModeEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGhostModeEngine>;
    deployContract(
      name: "PrivacyProcessor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivacyProcessor>;
    deployContract(
      name: "AgentCatcherOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentCatcherOracle>;
    deployContract(
      name: "ISomniaAgents",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaAgents>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
